import uuid
from typing import TYPE_CHECKING

from sqlalchemy import ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base
from app.db.models.mixins import SoftDeleteMixin, TimestampMixin, UUIDPKMixin

if TYPE_CHECKING:
    from app.db.models.asset import Asset
    from app.db.models.project import Project
    from app.db.models.story import Story


class Character(UUIDPKMixin, TimestampMixin, SoftDeleteMixin, Base):
    __tablename__ = "characters"

    # Nullable: a character can be generated standalone by the Character Architect
    # agent (from a Story that has no Project yet) before any Project exists to
    # attach it to - mirrors stories.project_id.
    project_id: Mapped[uuid.UUID | None] = mapped_column(
        PG_UUID(as_uuid=True), ForeignKey("projects.id", ondelete="CASCADE"), nullable=True
    )
    # Nullable: only set for characters generated by the Character Architect agent
    # from a specific Story; manually-created characters (generic /characters CRUD)
    # leave this unset.
    story_id: Mapped[uuid.UUID | None] = mapped_column(
        PG_UUID(as_uuid=True), ForeignKey("stories.id", ondelete="CASCADE"), nullable=True
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    visual_reference_asset_id: Mapped[uuid.UUID | None] = mapped_column(
        PG_UUID(as_uuid=True), ForeignKey("assets.id", ondelete="SET NULL"), nullable=True
    )
    voice_profile: Mapped[dict] = mapped_column(JSONB, default=dict, nullable=False)
    canonical_traits: Mapped[dict] = mapped_column(JSONB, default=dict, nullable=False)
    embedding_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    # Agent generation provenance: prompt_version, model, latency_ms, attempts,
    # prompt_tokens, completion_tokens, generated_at. Same blob duplicated across
    # every character produced by one agent run, mirroring stories.generation_metadata.
    generation_metadata: Mapped[dict] = mapped_column(JSONB, default=dict, nullable=False)

    project: Mapped["Project | None"] = relationship(back_populates="characters")
    story: Mapped["Story | None"] = relationship(back_populates="characters")
    visual_reference_asset: Mapped["Asset | None"] = relationship()
