"""make story project_id nullable add generation_metadata

Revision ID: 410777e1549f
Revises: 8c6a751fc7e8
Create Date: 2026-06-17 19:11:23.534547

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '410777e1549f'
down_revision: str | None = '8c6a751fc7e8'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'stories',
        sa.Column(
            'generation_metadata',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.alter_column('stories', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stories', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('stories', 'generation_metadata')
    # ### end Alembic commands ###
