"""add decision_points table

Revision ID: 57d67b51d876
Revises: a5a3c6aed31d
Create Date: 2026-06-20 09:10:50.320182

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '57d67b51d876'
down_revision: str | None = 'a5a3c6aed31d'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_points',
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('beat_index', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_hook', sa.String(length=1000), nullable=True),
    sa.Column('branch_candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decision_points')
    # ### end Alembic commands ###
