"""add butterfly score fields to branches

Revision ID: 8c6a751fc7e8
Revises: 9717ee790934
Create Date: 2026-06-17 17:52:58.799216

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8c6a751fc7e8'
down_revision: str | None = '9717ee790934'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('butterfly_score', sa.SmallInteger(), nullable=True))
    op.add_column('branches', sa.Column('probability', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('branches', sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('branches', sa.Column('stability_explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###
    # Alembic's autogenerate does not detect CheckConstraint changes; added manually
    # to match app/db/models/branch.py.
    op.create_check_constraint(
        'ck_branches_butterfly_score_range',
        'branches',
        'butterfly_score IS NULL OR (butterfly_score >= 0 AND butterfly_score <= 100)',
    )
    op.create_check_constraint(
        'ck_branches_probability_range',
        'branches',
        'probability IS NULL OR (probability >= 0 AND probability <= 100)',
    )
    op.create_check_constraint(
        'ck_branches_confidence_score_range',
        'branches',
        'confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 100)',
    )


def downgrade() -> None:
    op.drop_constraint('ck_branches_confidence_score_range', 'branches', type_='check')
    op.drop_constraint('ck_branches_probability_range', 'branches', type_='check')
    op.drop_constraint('ck_branches_butterfly_score_range', 'branches', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'stability_explanation')
    op.drop_column('branches', 'confidence_score')
    op.drop_column('branches', 'probability')
    op.drop_column('branches', 'butterfly_score')
    # ### end Alembic commands ###
