"""character architect: nullable project_id, add story_id and generation_metadata

Revision ID: a5a3c6aed31d
Revises: 410777e1549f
Create Date: 2026-06-20 08:22:27.442154

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a5a3c6aed31d'
down_revision: str | None = '410777e1549f'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('story_id', sa.UUID(), nullable=True))
    op.add_column(
        'characters',
        sa.Column(
            'generation_metadata',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.alter_column('characters', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'characters', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.alter_column('characters', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('characters', 'generation_metadata')
    op.drop_column('characters', 'story_id')
    # ### end Alembic commands ###
