"""add character_branch_states table

Revision ID: f3b9c1a2d7e4
Revises: 57d67b51d876
Create Date: 2026-06-21 10:00:00.000000

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f3b9c1a2d7e4'
down_revision: str | None = '57d67b51d876'
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None

# create_type=False: app/db/models/character_branch_state.py also defines this
# enum (via pg_enum()) and that model is imported into Base.metadata by
# env.py - letting op.create_table's column also auto-create the type fires
# CREATE TYPE twice in one DDL run ("type already exists"). Creating it once,
# explicitly, below is the documented workaround for native postgres enums.
drift_severity_enum = postgresql.ENUM('none', 'minor', 'major', name='drift_severity', create_type=False)


def upgrade() -> None:
    drift_severity_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_branch_states',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('state_diff', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('drift_severity', drift_severity_enum, nullable=False),
    sa.Column('drift_warning', sa.Text(), nullable=True),
    sa.Column('generation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'branch_id', name='uq_character_branch_states')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_branch_states')
    # ### end Alembic commands ###
    drift_severity_enum.drop(op.get_bind(), checkfirst=True)
